let countryDatabase = [
    ["Afghanistan", "Asia", "Kabul"],
    ["Albania", "Europe", "Tirana"],
    ["Algeria", "Africa", "Algiers"],
    ["Andorra", "Europe", "Andorra la Vella"],
    ["Angola", "Africa", "Luanda"],
    ["Antigua and Barbuda", "North America", "Saint John's"],
    ["Argentina", "South America", "Buenos Aires"],
    ["Armenia", "Asia", "Yerevan"],
    ["Australia", "Oceania", "Canberra"],
    ["Austria", "Europe", "Vienna"],
    ["Azerbaijan", "Asia", "Baku"],
    ["Bahamas", "North America", "Nassau"],
    ["Bahrain", "Asia", "Manama"],
    ["Bangladesh", "Asia", "Dhaka"],
    ["Barbados", "North America", "Bridgetown"],
    ["Belarus", "Europe", "Minsk"],
    ["Belgium", "Europe", "Brussels"],
    ["Belize", "North America", "Belmopan"],
    ["Benin", "Africa", "Porto-Novo"],
    ["Bhutan", "Asia", "Thimphu"],
    ["Bolivia", "South America", "La Paz and Sucre"],
    ["Bosnia and Herzegovina", "Europe", "Sarajevo"],
    ["Botswana", "Africa", "Gaborone"],
    ["Brazil", "South America", "Brasília"],
    ["Brunei", "Asia", "Bandar Seri Begawan"],
    ["Bulgaria", "Europe", "Sofia"],
    ["Burkina Faso", "Africa", "Ouagadougou"],
    ["Burundi", "Africa", "Bujumbura"],
    ["Cape Verde", "Africa", "Praia"],
    ["Cambodia", "Asia", "Phnom Penh"],
    ["Cameroon", "Africa", "Yaoundé"],
    ["Canada", "North America", "Ottawa"],
    ["Central African Republic", "Africa", "Bangui"],
    ["Chad", "Africa", "N'Djamena"],
    ["Chile", "South America", "Santiago"],
    ["China", "Asia", "Beijing"],
    ["Colombia", "South America", "Bogotá"],
    ["Comoros", "Africa", "Moroni"],
    ["Congo-Kinshasa", "Africa", "Kinshasa"],
    ["Congo-Brazzaville", "Africa", "Brazzaville"],
    ["Costa Rica", "North America", "San José"],
    ["Ivory Coast", "Africa", "Yamoussoukro"],
    ["Croatia", "Europe", "Zagreb"],
    ["Cuba", "North America", "Havana"],
    ["Cyprus", "Europe", "Nicosia"],
    ["Czechia", "Europe", "Prague"],
    ["Denmark", "Europe", "Copenhagen"],
    ["Djibouti", "Africa", "Djibouti"],
    ["Dominica", "North America", "Roseau"],
    ["Dominican Republic", "North America", "Santo Domingo"],
    ["East Timor", "Asia", "Dili"],
    ["Ecuador", "South America", "Quito"],
    ["Egypt", "Africa and Asia", "Cairo"],
    ["El Salvador", "North America", "San Salvador"],
    ["Equatorial Guinea", "Africa", "Malabo"],
    ["Eritrea", "Africa", "Asmara"],
    ["Estonia", "Europe", "Talinn"],
    ["Eswatini", "Africa", "Mbabane and Lobamba"],
    ["Ethiopia", "Africa", "Addis Ababa"],
    ["Fiji", "Oceania", "Suva"],
    ["Finland", "Europe", "Helsinki"],
    ["France", "Europe", "Paris"],
    ["Gabon", "Africa", "Libreville"],
    ["Gambia", "Africa", "Banjul"],
    ["Georgia", "Asia", "Tbilisi"],
    ["Germany", "Europe", "Berlin"],
    ["Ghana", "Africa", "Accra"],
    ["Greece", "Europe", "Athens"],
    ["Grenada", "North America", "St. George's"],
    ["Guatemala", "North America", "Guatemala City"],
    ["Guinea", "Africa", "Conakry"],
    ["Guinea-Bissau", "Africa", "Bissau"],
    ["Guyana", "South America", "Georgetown"],
    ["Haiti", "North America", "Port-au-Prince"],
    ["Honduras", "North America", "Tegucigalpa"],
    ["Hungary", "Europe", "Budapest"],
    ["Iceland", "Europe", "Reykjavik"],
    ["India", "Asia", "New Delhi"],
    ["Indonesia", "Asia", "Jakarta"],
    ["Iran", "Asia", "Tehrān"],
    ["Iraq", "Asia", "Baghdad"],
    ["Ireland", "Europe", "Dublin"],
    ["Israel", "Asia", "Jerusalem"],
    ["Italy", "Europe", "Rome"],
    ["Jamaica", "North America", "Kingston"],
    ["Japan", "Asia", "Tokyo"],
    ["Jordan", "Asia", "Amman"],
    ["Kazakhstan", "Europe and Asia", "Nur-Sultan"],
    ["Kenya", "Africa", "Nairobi"],
    ["Kiribati", "Oceania", "South Tarawa"],
    ["North Korea", "Asia", "P’yŏngyang"],
    ["South Korea", "Asia", "Seoul"],
    ["Kosovo", "Europe", "Pristina"],
    ["Kuwait", "Asia", "Kuwait"],
    ["Kyrgyzstan", "Asia", "Bishkek"],
    ["Laos", "Asia", "Vientiane"],
    ["Latvia", "Europe", "Riga"],
    ["Lebanon", "Asia", "Beirut"],
    ["Lesotho", "Africa", "Maseru"],
    ["Liberia", "Africa", "Monrovia"],
    ["Libya", "Africa", "Tripoli"],
    ["Liechtenstein", "Europe", "Vaduz"],
    ["Lithuania", "Europe", "Vilnius"],
    ["Luxembourg", "Europe", "Luxembourg"],
    ["Madagascar", "Africa", "Antananarivo"],
    ["Malawi", "Africa", "Lilongwe"],
    ["Malaysia", "Asia", "Kuala Lumpur"],
    ["Maldives", "Asia", "Male"],
    ["Mali", "Africa", "Bamako"],
    ["Malta", "Europe", "Valleta"],
    ["Marshall Islands", "Oceania", "Majuro"],
    ["Mauritania", "Africa", "Nouakchott"],
    ["Mauritius", "Africa", "Port Louis"],
    ["Mexico", "North America", "Mexico City"],
    ["Micronesia", "Oceania", "Palikir"],
    ["Moldova", "Europe", "Chișinău"],
    ["Monaco", "Europe", "Monaco"],
    ["Mongolia", "Asia", "Ulaanbaatar"],
    ["Montenegro", "Europe", "Podgorica"],
    ["Morocco", "Africa", "Rabat"],
    ["Mozambique", "Africa", "Maputo"],
    ["Myanmar", "Asia", "Nay Pyi Taw"],
    ["Namibia", "Africa", "Windhoek"],
    ["Nauru", "Oceania", "Yaren"],
    ["Nepal", "Asia", "Kathmandu"],
    ["Netherlands", "Europe", "Amsterdam"],
    ["New Zealand", "Oceania", "Wellington"],
    ["Nicaragua", "North America", "Managua"],
    ["Niger", "Africa", "Niamey"],
    ["Nigeria", "Africa", "Abuja"],
    ["North Macedonia", "Europe", "Skopje"],
    ["Norway", "Europe", "Oslo"],
    ["Oman", "Asia", "Muscat"],
    ["Pakistan", "Asia", "Islamabad"],
    ["Palau", "Oceania", "Ngerulmud"],
    ["Palestine", "Asia", "Ramallah or East Jerusalem"],
    ["Panama", "North America", "Panama City"],
    ["Papua New Guinea", "Oceania", "Port Moresby"],
    ["Paraguay", "South America", "Asunción"],
    ["Peru", "South America", "Lima"],
    ["Philippines", "Asia", "Manila"],
    ["Poland", "Europe", "Warsaw"],
    ["Portugal", "Europe", "Lisbon"],
    ["Qatar", "Asia", "Doha"],
    ["Romania", "Europe", "Bucharest"],
    ["Russia", "Europe and Asia", "Moscow"],
    ["Rwanda", "Africa", "Kigali"],
    ["Saint Kitts and Nevis", "North America", "Basseterre"],
    ["Saint Lucia", "North America", "Castries"],
    ["Saint Vincent and the Grenadines", "North America", "Kingstown"],
    ["Samoa", "Oceania", "Apia"],
    ["San Marino", "Europe", "San Marino"],
    ["Sao Tome and Principe", "Africa", "São Tomé"],
    ["Saudi Arabia", "Asia", "Riyadh"],
    ["Senegal", "Africa", "Dakar"],
    ["Serbia", "Europe", "Belgrade"],
    ["Seychelles", "Africa", "Victoria"],
    ["Sierra Leone", "Africa", "Freetown"],
    ["Singapore", "Asia", "Singapore"],
    ["Slovakia", "Europe", "Bratislava"],
    ["Slovenia", "Europe", "Ljubljana"],
    ["Solomon Islands", "Oceania", "Honiara"],
    ["Somalia", "Africa", "Mogadishu"],
    ["South Africa", "Africa", "Pretoria, Cape Town, and Bloemfontein"],
    ["Spain", "Europe", "Madrid"],
    ["Sri Lanka", "Asia", "Colombo and Sri Jayewardenepura Kotte"],
    ["Sudan", "Africa", "Khartoum"],
    ["South Sudan", "Africa", "Juba"],
    ["Suriname", "South America", "Paramaribo"],
    ["Sweden", "Europe", "Stockholm"],
    ["Switzerland", "Europe", "Bern"],
    ["Syria", "Asia", "Damascus"],
    ["Taiwan", "Asia", "Taipei"],
    ["Tajikistan", "Asia", "Dushanbe"],
    ["Tanzania", "Africa", "Dodoma"],
    ["Thailand", "Asia", "Bangkok"],
    ["Togo", "Africa", "Lomé"],
    ["Tonga", "Oceania", "Nukuʿalofa"],
    ["Trinidad and Tobago", "North America", "Port of Spain"],
    ["Tunisia", "Africa", "Tunis"],
    ["Turkey", "Europe and Asia", "Ankara"],
    ["Turkmenistan", "Asia", "Ashgabat"],
    ["Tuvalu", "Oceania", "Funafuti"],
    ["Uganda", "Africa", "Kampala"],
    ["Ukraine", "Europe", "Kyiv"],
    ["United Arab Emirates", "Asia", "Abu Dhabi"],
    ["United Kingdom", "Europe", "London"],
    ["United States", "North America", "Washington, D.C."],
    ["Uruguay", "South America", "Montevideo"],
    ["Uzbekistan", "Asia", "Tashkent"],
    ["Vanuatu", "Oceania", "Port-Vila"],
    ["Vatican City", "Europe", "Vatican City"],
    ["Venezuela", "South America", "Caracas"],
    ["Vietnam", "Asia", "Hanoi"],
    ["Yemen", "Asia", "Sanaa"],
    ["Zambia", "Africa", "Lusaka"],
    ["Zimbabwe", "Africa", "Harare"]
]
let countryNumber = Int.random(in: 0...(countryDatabase.count - 1))
while true {
    print("This country starts with the letter \(countryDatabase[countryNumber][0][countryDatabase[countryNumber][0].index(countryDatabase[countryNumber][0].startIndex, offsetBy: 0)]), is in the continent(s) of \(countryDatabase[countryNumber][1]), and has the capital(s) of \(countryDatabase[countryNumber][2]).")
    print("Guess the country:", terminator: " ")
    let answer = readLine()
    if answer == countryDatabase[countryNumber][0] {
        print("Correct! The answer is \(countryDatabase[countryNumber][0])."); break
    } else {
        print("Incorrect! Please try again.")
    }
}